version: '3'

services:
  bot:
    build:
      context: .
    env_file:
      - ./vars.env
    restart: unless-stopped
    depends_on:
      - memcached

  memcached:
    image: memcached
    restart: unless-stopped